"""Type stubs for the ``pycedar`` extension module (PEP 561 stub-only package).

(拡張モジュール ``pycedar`` の型スタブ。実体は Cython で書かれているため、
IDE や型検査器はこのスタブを通して API を参照する)

Value semantics that stubs cannot express fully:

* every value is a C ``int``; ``-1`` (``base_trie.NO_VALUE``) and ``-2``
  (``base_trie.NO_PATH``) are reserved sentinels and rejected by writers.
* keys are ``str`` (encoded as UTF-8 internally) or ``bytes``; ``str`` keys
  must not contain a NUL byte.
"""

from typing import Any, Iterator, overload
from typing import TypeVar

import builtins

__version__: str

_T = TypeVar("_T")

class node:
    """A cursor into a trie. (トライ内の位置を指すカーソル)"""

    id: int
    length: int
    root: int
    def key(self) -> str | bytes: ...
    def value(self) -> int: ...
    def track(self) -> tuple[int, int, int]: ...
    def traverse(self, key: str | bytes) -> Iterator[tuple[int, int, int]]: ...
    def find_nodes(self, key: str | bytes) -> Iterator[node]: ...
    def get_node(self, key: str | bytes) -> node | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class base_trie:
    """Base class of every trie; use a specialized subclass.
    (全トライの基底クラス。直接使わず特殊化クラスを使う)"""

    NO_VALUE: int
    NO_PATH: int
    root: node

    def clear(self, reuse: bool = True) -> None: ...

    def capacity(self) -> int: ...
    def size(self) -> int: ...
    def length(self) -> int: ...
    def total_size(self) -> int: ...
    def unit_size(self) -> int: ...
    def nonzero_size(self) -> int: ...
    def nonzero_length(self) -> int: ...
    def num_keys(self) -> int: ...

    def begin(self, from_id: int = 0, length: int = 0) -> tuple[int, int, int]: ...
    def next(self, node_id: int, length: int, root: int = 0) -> tuple[int, int, int]: ...

    def open(self, filepath: str, mode: str = "rb", offset: int = 0, size: int = 0) -> int: ...
    def save(self, filepath: str, mode: str = "wb", shrink: bool = True) -> int: ...
    def dumps(self, shrink: bool = True) -> bytes: ...
    def loads(self, data: bytes) -> int: ...

    def __reduce__(self) -> tuple[Any, tuple[Any, ...]]: ...

class str_trie(base_trie):
    def common_prefix_predict(
        self, key: str, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[str, int, int]]: ...
    def common_prefix_search(
        self, key: str, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[str, int, int]]: ...
    def erase(self, key: str, from_id: int = 0) -> int: ...
    def exact_match_search(self, key: str, from_id: int = 0) -> tuple[int, int, int]: ...
    def set(self, key: str, value: int) -> int: ...
    def suffix(self, node_id: int, length: int = 0) -> str: ...
    def traverse(self, key: str, from_id: int = 0, pos: int = 0) -> tuple[int, int, int]: ...
    def update(self, key: str, delta: int = 0) -> int: ...

class bytes_trie(base_trie):
    def common_prefix_predict(
        self, key: bytes, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[bytes, int, int]]: ...
    def common_prefix_search(
        self, key: bytes, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[bytes, int, int]]: ...
    def erase(self, key: bytes, from_id: int = 0) -> int: ...
    def exact_match_search(self, key: bytes, from_id: int = 0) -> tuple[int, int, int]: ...
    def set(self, key: bytes, value: int) -> int: ...
    def suffix(self, node_id: int, length: int = 0) -> bytes: ...
    def traverse(self, key: bytes, from_id: int = 0, pos: int = 0) -> tuple[int, int, int]: ...
    def update(self, key: bytes, delta: int = 0) -> int: ...

class unicode_trie(base_trie):
    # On Python 3 this behaves identically to str_trie.
    # (Python 3 では str_trie と同一の挙動。後方互換のために残っている)
    def common_prefix_predict(
        self, key: str, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[str, int, int]]: ...
    def common_prefix_search(
        self, key: str, from_id: int = 0, max_size: int = -1,
    ) -> list[tuple[str, int, int]]: ...
    def erase(self, key: str, from_id: int = 0) -> int: ...
    def exact_match_search(self, key: str, from_id: int = 0) -> tuple[int, int, int]: ...
    def set(self, key: str, value: int) -> int: ...
    def suffix(self, node_id: int, length: int = 0) -> str: ...
    def traverse(self, key: str, from_id: int = 0, pos: int = 0) -> tuple[int, int, int]: ...
    def update(self, key: str, delta: int = 0) -> int: ...

class dict:
    """A dict-like facade over a trie. (dict 風のファサード)

    The key type is chosen by the constructor at runtime (``str`` by default,
    or ``bytes``), which a stub cannot express; every key is typed as the union
    of the two possibilities.
    (キー型は実行時にコンストラクタで選ばれるためスタブでは表現できない。
     各キーは取りうる2型の共用型になっている)
    """

    trie: base_trie
    root: node
    type: builtins.type

    def __init__(self, type: builtins.type[str | bytes] = str) -> None: ...

    @overload
    def get(self, key: str | bytes) -> int: ...
    @overload
    def get(self, key: str | bytes, default: _T) -> int | _T: ...

    def get_node(self, key: str | bytes) -> node | None: ...

    @overload
    def pop(self, key: str | bytes) -> int: ...
    @overload
    def pop(self, key: str | bytes, default: _T) -> int | _T: ...

    def popitem(self) -> tuple[str | bytes, int]: ...

    def set(self, key: str | bytes, value: int) -> int: ...
    def setdefault(self, key: str | bytes, value: int = 0) -> int: ...
    def update(self, key: str | bytes, delta: int = 0) -> int: ...

    def clear(self) -> None: ...

    def keys(self) -> Iterator[str | bytes]: ...
    def values(self) -> Iterator[int]: ...
    def items(self) -> Iterator[tuple[str | bytes, int]]: ...
    def nodes(self) -> Iterator[node]: ...

    def find(self, key: str | bytes) -> Iterator[tuple[str | bytes, int]]: ...
    def find_keys(self, key: str | bytes) -> Iterator[str | bytes]: ...
    def find_values(self, key: str | bytes) -> Iterator[int]: ...

    def load(self, filepath: str, mode: str = "rb") -> int: ...
    def save(self, filepath: str, mode: str = "wb", shrink: bool = True) -> int: ...
    def dumps(self, shrink: bool = True) -> bytes: ...
    def loads(self, data: bytes) -> int: ...

    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str | bytes]: ...
    def __getitem__(self, key: str | bytes) -> int: ...
    def __setitem__(self, key: str | bytes, value: int) -> None: ...
    def __delitem__(self, key: str | bytes) -> None: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, ...]]: ...